#ifndef UCI_PDL_H
#define UCI_PDL_H

/*
 * Protocol constants in this header are the repository's authoritative UCI
 * definitions. Standard UCI message/group/opcode values follow the Android UWB
 * definitions; Qorvo vendor groups/opcodes extend that surface with values
 * cross-checked against the Qorvo SDK Cherry C headers.
 */

#include "uci_opcode_constants.h"

// Message Type (MT) definitions - aligned with Android UWB spec
#define DATA            0x00
#define COMMAND         0x01
#define RESPONSE        0x02
#define NOTIFICATION    0x03

// Packet Boundary Flag (PBF) definitions - aligned with Android UWB spec
#define COMPLETE        0x00
#define NOT_COMPLETE    0x01

/*
 * Group ID (GID) definitions.
 * Standard groups track Android UWB definitions. Qorvo vendor groups track the
 * Cherry C headers in the local SDK tree; in particular, GID 0x0E follows
 * Cherry's QORVO_MAC assignment rather than the Python-tool ConfigManager alias.
 */
#define CORE            0x00
#define SESSION_CONFIG  0x01
#define SESSION_CONTROL 0x02
#define QORVO_EXT1      0x09
#define QORVO_EXT2      0x0B
#define ANDROID         0x0C
#define TEST            0x0D
#define QORVO_MAC       0x0E
#define QORVO_CALIB     0x0F

// OID (Opcode ID) definitions for CORE group - aligned with Android UWB spec
#define CORE_DEVICE_RESET         0x00
#define CORE_DEVICE_STATUS_NTF    0x01
#define CORE_DEVICE_INFO          0x02
#define CORE_GET_CAPS_INFO        0x03
#define CORE_SET_CONFIG           0x04
#define CORE_GET_CONFIG           0x05
#define CORE_DEVICE_SUSPEND       0x06
#define CORE_GENERIC_ERROR_NTF    0x07
#define CORE_QUERY_UWBS_TIMESTAMP 0x08

// OID (Opcode ID) definitions for Session Config group - aligned with Android UWB spec
#define SESSION_INIT                                  0x00
#define SESSION_DEINIT                                0x01
#define SESSION_STATUS_NTF                            0x02
#define SESSION_SET_APP_CONFIG                        0x03
#define SESSION_GET_APP_CONFIG                        0x04
#define SESSION_GET_COUNT                             0x05
#define SESSION_GET_STATE                             0x06
#define SESSION_UPDATE_CONTROLLER_MULTICAST_LIST      0x07
#define SESSION_UPDATE_ACTIVE_ROUNDS_ANCHOR           0x08
#define SESSION_UPDATE_ACTIVE_ROUNDS_DT_TAG           0x09
#define SESSION_SET_INITIATOR_DT_ANCHOR_RR_RDM_LIST   0x0a
#define SESSION_QUERY_DATA_SIZE_IN_RANGING            0x0b
#define SESSION_SET_HYBRID_CONTROLLER_CONFIG          0x0c
#define SESSION_SET_HYBRID_CONTROLEE_CONFIG           0x0d
#define SESSION_DATA_TRANSFER_PHASE_CONFIG            0x0e

// OID (Opcode ID) definitions for Session Control group - aligned with Android UWB spec
#define SESSION_START               0x00
#define SESSION_STOP                0x01
#define SESSION_RESERVED            0x02
#define SESSION_GET_RANGING_COUNT   0x03
#define SESSION_DATA_CREDIT_NTF     0x04
#define SESSION_DATA_TRANSFER_STATUS_NTF 0x05
#define SESSION_INFO_NTF            0x00
#define SESSION_INFO_NTF_OPCODE     SESSION_INFO_NTF
#define SESSION_LOGICAL_LINK_CREATE 0x07
#define SESSION_LOGICAL_LINK_CLOSE  0x08
#define SESSION_LOGICAL_LINK_UWBS_CLOSE 0x09
#define SESSION_LOGICAL_LINK_UWBS_CREATE 0x0A
#define SESSION_LOGICAL_LINK_GET_PARAM 0x0B

// Session types - aligned with Android UWB spec

// Status definitions - aligned with Android UWB spec
#define UCI_STATUS_OK                           0x00
#define UCI_STATUS_REJECTED                     0x01
#define UCI_STATUS_FAILED                       0x02
#define UCI_STATUS_SYNTAX_ERROR                 0x03
#define UCI_STATUS_INVALID_PARAM                0x04
#define UCI_STATUS_INVALID_RANGE                0x05
#define UCI_STATUS_INVALID_MSG_SIZE             0x06
#define UCI_STATUS_UNKNOWN_GID                  0x07
#define UCI_STATUS_UNKNOWN_OID                  0x08
#define UCI_STATUS_READ_ONLY                    0x09
#define UCI_STATUS_COMMAND_RETRY                0x0A
#define UCI_STATUS_UNKNOWN                      0x0B
#define UCI_STATUS_NOT_APPLICABLE               0x0C

// UWB Session Specific Status Codes
#define UCI_STATUS_SESSION_NOT_EXIST            0x11
#define UCI_STATUS_SESSION_DUPLICATE            0x12
#define UCI_STATUS_SESSION_ACTIVE               0x13
#define UCI_STATUS_MAX_SESSIONS_EXCEEDED        0x14
#define UCI_STATUS_SESSION_NOT_CONFIGURED       0x15
#define UCI_STATUS_ACTIVE_SESSIONS_ONGOING      0x16
#define UCI_STATUS_MULTICAST_LIST_FULL          0x17
#define UCI_STATUS_ADDRESS_NOT_FOUND            0x18
#define UCI_STATUS_ADDRESS_ALREADY_PRESENT      0x19
#define UCI_STATUS_ERROR_UWB_INITIATION_TIME_TOO_OLD 0x1A
#define UCI_STATUS_OK_NEGATIVE_DISTANCE_REPORT  0x1B

// UWB Ranging Session Specific Status Codes
#define UCI_STATUS_RANGING_TX_FAILED            0x20
#define UCI_STATUS_RANGING_RX_TIMEOUT           0x21
#define UCI_STATUS_RANGING_RX_PHY_DEC_FAILED    0x22
#define UCI_STATUS_RANGING_RX_PHY_TOA_FAILED    0x23
#define UCI_STATUS_RANGING_RX_PHY_STS_FAILED    0x24
#define UCI_STATUS_RANGING_RX_MAC_DEC_FAILED    0x25
#define UCI_STATUS_RANGING_RX_MAC_IE_DEC_FAILED 0x26
#define UCI_STATUS_RANGING_RX_MAC_IE_MISSING    0x27
#define UCI_STATUS_ERROR_ROUND_INDEX_NOT_ACTIVATED 0x28
#define UCI_STATUS_ERROR_NUMBER_OF_ACTIVE_RANGING_ROUNDS_EXCEEDED 0x29
#define UCI_STATUS_ERROR_DL_TDOA_DEVICE_ADDRESS_NOT_MATCHING_IN_REPLY_TIME_LIST 0x2A

// Device state definitions - aligned with Android UWB spec
#define DEVICE_STATE_READY      0x01
#define DEVICE_STATE_ACTIVE     0x02
#define DEVICE_STATE_ERROR      0xFF

// Session state definitions
#define SESSION_STATE_INIT      0x00
#define SESSION_STATE_DEINIT    0x01
#define SESSION_STATE_ACTIVE    0x02
#define SESSION_STATE_IDLE      0x03

// Reset type definitions - aligned with Android UWB spec
#define UWBS_RESET              0x00

// Application configuration TLV types - aligned with Android UWB spec
typedef enum {
    DEVICE_TYPE = 0x00,
    RANGING_ROUND_USAGE = 0x01,
    STS_CONFIG = 0x02,
    MULTI_NODE_MODE = 0x03,
    CHANNEL_NUMBER = 0x04,
    NO_OF_CONTROLEE = 0x05,
    DEVICE_MAC_ADDRESS = 0x06,
    DST_MAC_ADDRESS = 0x07,
    SLOT_DURATION = 0x08,
    RANGING_DURATION = 0x09,
    STS_INDEX = 0x0A,
    MAC_FCS_TYPE = 0x0B,
    RANGING_ROUND_CONTROL = 0x0C,
    AOA_RESULT_REQ = 0x0D,
    RNG_DATA_NTF = 0x0E,
    RNG_DATA_NTF_PROXIMITY_NEAR = 0x0F,
    RNG_DATA_NTF_PROXIMITY_FAR = 0x10,
    DEVICE_ROLE = 0x11,
    RFRAME_CONFIG = 0x12,
    RSSI_REPORTING = 0x13,
    PREAMBLE_CODE_INDEX = 0x14,
    SFD_ID = 0x15,
    PSDU_DATA_RATE = 0x16,
    PREAMBLE_DURATION = 0x17,
    LINK_LAYER_MODE = 0x18,
    DATA_REPETITION_COUNT = 0x19,
    RANGING_TIME_STRUCT = 0x1A,
    SLOTS_PER_RR = 0x1B,
    TX_ADAPTIVE_PAYLOAD_POWER = 0x1C,
    RNG_DATA_NTF_AOA_BOUND = 0x1D,
    RESPONDER_SLOT_INDEX = 0x1E,
    PRF_MODE = 0x1F,
    CAP_SIZE_RANGE = 0x20,
    TX_JITTER_WINDOW_SIZE = 0x21,
    SCHEDULED_MODE = 0x22,
    KEY_ROTATION = 0x23,
    KEY_ROTATION_RATE = 0x24,
    SESSION_PRIORITY = 0x25,
    MAC_ADDRESS_MODE = 0x26,
    VENDOR_ID = 0x27,
    STATIC_STS_IV = 0x28,
    NUMBER_OF_STS_SEGMENTS = 0x29,
    MAX_RR_RETRY = 0x2A,
    UWB_INITIATION_TIME = 0x2B,
    HOPPING_MODE = 0x2C,
    BLOCK_STRIDE_LENGTH = 0x2D,
    RESULT_REPORT_CONFIG = 0x2E,
    IN_BAND_TERMINATION_ATTEMPT_COUNT = 0x2F,
    SUB_SESSION_ID = 0x30,
    BPRF_PHR_DATA_RATE = 0x31,
    MAX_NUMBER_OF_MEASUREMENTS = 0x32,
    UL_TDOA_TX_INTERVAL = 0x33,
    UL_TDOA_RANDOM_WINDOW = 0x34,
    STS_LENGTH = 0x35,
    SUSPEND_RANGING_ROUNDS = 0x36,
    UL_TDOA_NTF_REPORT_CONFIG = 0x37,
    UL_TDOA_DEVICE_ID = 0x38,
    UL_TDOA_TX_TIMESTAMP = 0x39,
    MIN_FRAMES_PER_RR = 0x3A,
    MTU_SIZE = 0x3B,
    INTER_FRAME_INTERVAL = 0x3C,
    DL_TDOA_RANGING_METHOD = 0x3D,
    DL_TDOA_TX_TIMESTAMP_CONF = 0x3E,
    DL_TDOA_HOP_COUNT = 0x3F,
    DL_TDOA_ANCHOR_CFO = 0x40,
    DL_TDOA_ANCHOR_LOCATION = 0x41,
    DL_TDOA_TX_ACTIVE_RANGING_ROUNDS = 0x42,
    DL_TDOA_BLOCK_STRIDING = 0x43,
    DL_TDOA_TIME_REFERENCE_ANCHOR = 0x44,
    SESSION_KEY = 0x45,
    SUBSESSION_KEY = 0x46,
    SESSION_DATA_TRANSFER_STATUS_NTF_CONFIG = 0x47,
    SESSION_TIME_BASE = 0x48,
    DL_TDOA_RESPONDER_TOF = 0x49,
    SECURE_RANGING_NEFA_LEVEL = 0x4A,
    SECURE_RANGING_CSW_LENGTH = 0x4B,
    APPLICATION_DATA_ENDPOINT = 0x4C,
    OWR_AOA_MEASUREMENT_NTF_PERIOD = 0x4D,
    CCC_HOP_MODE_KEY = 0xA0,
    CCC_UWB_TIME0 = 0xA1,
    CCC_RANGING_PROTOCOL_VER = 0xA3,
    CCC_UWB_CONFIG_ID = 0xA4,
    CCC_PULSESHAPE_COMBO = 0xA5,
    CCC_URSK_TTL = 0xA6,
    CCC_LAST_INDEX_USED = 0xA8,
    ALIRO_MAC_MODE = 0xA9,
    NB_OF_RANGE_MEASUREMENTS = 0xE3,
    NB_OF_AZIMUTH_MEASUREMENTS = 0xE4,
    NB_OF_ELEVATION_MEASUREMENTS = 0xE5,
    ENABLE_DIAGNOSTICS = 0xE8,
    DIAGRAMS_FRAME_REPORTS_FIELDS = 0xE9,
    ANTENNA_MODE = 0xEA,
} AppConfigTlvType;

// Device configuration IDs - aligned with Android UWB spec
typedef enum {
    DEVICE_STATE = 0x00,
    LOW_POWER_MODE = 0x01,
    DEVICE_CHANNEL = 0xA0,
    DEVICE_PREAMBLE_CODE = 0xA1,
    DEVICE_PAN_ID = 0xA2,
    DEVICE_SHORT_ADDR = 0xA3,
    DEVICE_EXTENDED_ADDR = 0xA4,
    DEVICE_PAN_COORD = 0xA5,
    DEVICE_PROMISCUOUS = 0xA6,
    DEVICE_FRAME_RETRIES = 0xA7,
    DEVICE_TRACES = 0xA8,
    DEVICE_PM_MIN_INACTIVITY_S4 = 0xA9,
} DeviceConfigId;

// Session types - aligned with Android UWB spec
typedef enum {
    FIRA_RANGING_SESSION = 0x00,
    FIRA_RANGING_AND_IN_BAND_DATA_SESSION = 0x01,
    FIRA_DATA_TRANSFER_SESSION = 0x02,
    FIRA_RANGING_ONLY_PHASE = 0x03,
    FIRA_IN_BAND_DATA_PHASE = 0x04,
    FIRA_RANGING_WITH_DATA_PHASE = 0x05,
    CCC_RANGING_SESSION = 0xA0,
    DEVICE_TEST_MODE = 0xD0,
} SessionType;

typedef enum {
    FRAME_REPORT_TLV_RSSI = 0x00,
    FRAME_REPORT_TLV_AOA = 0x01,
    FRAME_REPORT_TLV_CIR = 0x02,
    FRAME_REPORT_TLV_SEGMENT_METRICS = 0x06,
} FrameReportTlvType;

typedef enum {
    MULTICAST_ACTION_ADD = 0x00,
    MULTICAST_ACTION_REMOVE = 0x01,
    MULTICAST_ACTION_ADD_SHORT_KEY = 0x02,
    MULTICAST_ACTION_ADD_LONG_KEY = 0x03,
} UpdateMulticastListAction;

// Capability TLV types - aligned with Android UWB spec
typedef enum {
    SUPPORTED_V1_FIRA_PHY_VERSION_RANGE_V2_MAX_MESSAGE_SIZE = 0x00,
    SUPPORTED_V1_FIRA_MAC_VERSION_RANGE_V2_MAX_DATA_PAYLOAD_SIZE = 0x01,
    SUPPORTED_V1_DEVICE_ROLES_V2_FIRA_PHY_VERSION_RANGE = 0x02,
    SUPPORTED_V1_RANGING_METHOD_V2_FIRA_MAC_VERSION_RANGE = 0x03,
    SUPPORTED_V1_STS_CONFIG_V2_DEVICE_TYPE = 0x04,
    SUPPORTED_V1_MULTI_NODE_MODES_V2_DEVICE_ROLES = 0x05,
    SUPPORTED_V1_RANGING_TIME_STRUCT_V2_RANGING_METHOD = 0x06,
    SUPPORTED_V1_SCHEDULED_MODE_V2_STS_CONFIG = 0x07,
    SUPPORTED_V1_HOPPING_MODE_V2_MULTI_NODE_MODE = 0x08,
    SUPPORTED_V1_BLOCK_STRIDING_V2_RANGING_TIME_STRUCT = 0x09,
    SUPPORTED_V1_UWB_INITIATION_TIME_V2_SCHEDULE_MODE = 0x0A,
    SUPPORTED_V1_CHANNELS_V2_HOPPING_MODE = 0x0B,
    SUPPORTED_V1_RFRAME_CONFIG_V2_BLOCK_STRIDING = 0x0C,
    SUPPORTED_V1_CC_CONSTRAINT_LENGTH_V2_UWB_INITIATION_TIME = 0x0D,
    SUPPORTED_V1_BPRF_PARAMETER_SETS_V2_CHANNELS = 0x0E,
    SUPPORTED_V1_HPRF_PARAMETER_SETS_V2_RFRAME_CONFIG = 0x0F,
    SUPPORTED_V1_AOA_V2_AOA_SUPPORT = 0x10,
    SUPPORTED_V1_EXTENDED_MAC_ADDRESS_V2_EXTENDED_MAC_ADDRESS = 0x11,
    SUPPORTED_V1_MAX_MESSAGE_SIZE_V2_ASSIGNED = 0x12,
    SUPPORTED_V1_MAX_DATA_PACKET_PAYLOAD_SIZE_V2_SESSION_KEY_LENGTH = 0x13,
    SUPPORTED_V2_EXTENDED_MAC_ADDRESS = 0x14,
    SUPPORTED_V2_ASSIGNED = 0x15,
    SUPPORTED_V2_SESSION_KEY_LENGTH = 0x16,
    SUPPORTED_V2_DT_ANCHOR_MAX_ACTIVE_RR = 0x17,
    SUPPORTED_V2_DT_TAG_MAX_ACTIVE_RR = 0x18,
    SUPPORTED_V2_DT_TAG_BLOCK_SHIPPING = 0x19,
    SUPPORTED_V2_PSDU_LENGTH_SUPPORT = 0x1A,
    CCC_SUPPORTED_CHAPS_PER_SLOT = 0xA0,
    CCC_SUPPORTED_SYNC_CODES = 0xA1,
    CCC_SUPPORTED_HOPPING_CONFIG_MODES_AND_SEQUENCES = 0xA2,
    CCC_SUPPORTED_CHANNELS = 0xA3,
    CCC_SUPPORTED_VERSIONS = 0xA4,
    CCC_SUPPORTED_UWB_CONFIGS = 0xA5,
    CCC_SUPPORTED_PULSE_SHAPE_COMBOS = 0xA6,
    CCC_SUPPORTED_RAN_MULTIPLIER = 0xA7,
    CCC_SUPPORTED_MAX_RANGING_SESSION_NUMBER = 0xA8,
    CCC_SUPPORTED_MIN_UWB_INITIATION_TIME_MS = 0xA9,
    CCC_PRIORITIZED_CHANNEL_LIST = 0xAA,
    CCC_SUPPORTED_UWBS_MAX_PPM = 0xAB,
    ALIRO_SUPPORTED_MAC_MODES = 0xAC,
    RADAR_SUPPORT = 0xB0,
    SUPPORTED_POWER_STATS = 0xC0,
    SUPPORTED_AOA_RESULT_REQ_ANTENNA_INTERLEAVING = 0xE3,
    SUPPORTED_MIN_RANGING_INTERVAL_MS = 0xE4,
    SUPPORTED_RANGE_DATA_NTF_CONFIG = 0xE5,
    SUPPORTED_RSSI_REPORTING = 0xE6,
    SUPPORTED_DIAGNOSTICS = 0xE7,
    SUPPORTED_MIN_SLOT_DURATION_RSTU = 0xE8,
    SUPPORTED_MAX_RANGING_SESSION_NUMBER = 0xE9,
} CapTlvType;

// Data transfer status codes
#define UCI_DATA_TRANSFER_STATUS_REPETITION_OK 0x00
#define UCI_DATA_TRANSFER_STATUS_OK 0x01
#define UCI_DATA_TRANSFER_STATUS_ERROR_DATA_TRANSFER 0x02
#define UCI_DATA_TRANSFER_STATUS_ERROR_NO_CREDIT_AVAILABLE 0x03
#define UCI_DATA_TRANSFER_STATUS_ERROR_REJECTED 0x04
#define UCI_DATA_TRANSFER_STATUS_SESSION_TYPE_NOT_SUPPORTED 0x05
#define UCI_DATA_TRANSFER_STATUS_ERROR_DATA_TRANSFER_IS_ONGOING 0x06
#define UCI_DATA_TRANSFER_STATUS_INVALID_FORMAT 0x07

// Reason codes for notifications
typedef enum {
    STATE_CHANGE_WITH_SESSION_MANAGEMENT_COMMANDS = 0x00,
    MAX_RANGING_ROUND_RETRY_COUNT_REACHED = 0x01,
    MAX_NUMBER_OF_MEASUREMENTS_REACHED = 0x02,
    SESSION_SUSPENDED_DUE_TO_INBAND_SIGNAL = 0x03,
    SESSION_RESUMED_DUE_TO_INBAND_SIGNAL = 0x04,
    SESSION_STOPPED_DUE_TO_INBAND_SIGNAL = 0x05,
} ReasonCode;

#endif // UCI_PDL_H
